# Generated by Django 4.0.1 on 2022-01-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_description_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb_image',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails'),
        ),
    ]
