# Generated by Django 4.0.1 on 2022-01-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_thumb_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumb_image',
            new_name='thumbnail_image',
        ),
    ]
